name: "NPM Audit Report - PR"

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: NPM Audit Comment
        uses: wx-jayesh/actions-npm-audit-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
